project:
  type: website
  output-dir: docs
  execute-dir: project
  
website:
  title: "EndingLoneliness"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: About.qmd
        text: AboutX
      - href: iFrame.qmd
        text: Questionnaire iFrame
      - href: survey analysis/surveyanalysis.qmd
        text: Static Report
      - href: SentimentAnalysis.qmd
        text: Sentiment Analysis
      - href: SignUp.qmd
        text: Sign Up
    
        
        
    logo: images/Ending_Loneliness_Logo.png
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


